### PR TITLE
add: badge.css styles

### PR DESCRIPTION
**Pull request by shilpe26**
Made Badge Component with features:-
🔹Simple Profile Badge
🔹Badge on Icons

Badge

### CODE REVIEW

**Comment by SJTGSHIVAM** [comment]
Can you add the html file shown in gif as part of same pull request.
image
I couldn't find the HTML file within badge branch . 
If it is there in dev or any other branch you can simply merge that branch to badge branch.
Do let me know your views on that @shilpe26 .
In case you are planning to add it as a different pr or directly it is also fine So I don't find any issues.
Looks good to merge.

**Review by SJTGSHIVAM — APPROVED** [review]
As per discussion... things look good

**Comment by shilpe26** [comment]
added badge.html file

**Comment by SJTGSHIVAM** [comment]
Now I don't see any issues in the desktop version of this feature we are good to merge.

**Comment by shilpe26** [comment]
Done the suggested changes.

**Pull request merged**
