### PR TITLE
add: alert component

### PR DESCRIPTION
**Pull request by shilpe26**
Made Alert component with two features:-
🔹Simple Alert 
🔹Outline Alerts are created by using alert class, followed by outline-variant.

alert

### CODE REVIEW

**Review by VedanthB — APPROVED** [review]
looks good 🚀

**Review by xsaurabhsuthar — APPROVED** [review]
Looks good.

**Comment by rahulk31** [comment]
Looks great, just that one small thing: the alert statement within the box should be aligned vertically, for now its more touching to the top border. display: flex and align-items: center can help there. Can go with other approach too.

Overall, its clean and good. 🚀

**Comment by shilpe26** [comment]
Done changes:-
Give Alert some top so that it don't like touching the top as suggested.

**Pull request merged**
